import streamlit as st
import json
from datetime import datetime
from researcher import run_research
from pdf_export import generate_pdf
from pdf_export import generate_pdf

st.set_page_config(
    page_title="Identity Research Tool",
    page_icon="🔍",
    layout="wide"
)

# --- Styling ---
st.markdown("""
<style>
    .gdpr-box {
        background: #fff8e1;
        border-left: 4px solid #f59e0b;
        padding: 12px 16px;
        border-radius: 4px;
        font-size: 0.85rem;
        margin-bottom: 1rem;
    }
    .review-box {
        background: #fef3c7;
        border: 1px solid #fcd34d;
        padding: 12px 16px;
        border-radius: 6px;
        margin-bottom: 1rem;
    }
    .risk-high   { background:#fee2e2; border-left:4px solid #ef4444; padding:8px 12px; border-radius:4px; margin:4px 0; }
    .risk-medium { background:#fef9c3; border-left:4px solid #eab308; padding:8px 12px; border-radius:4px; margin:4px 0; }
    .risk-low    { background:#dcfce7; border-left:4px solid #22c55e; padding:8px 12px; border-radius:4px; margin:4px 0; }
    .score-badge { font-size:2.5rem; font-weight:700; }
</style>
""", unsafe_allow_html=True)

# --- Header ---
st.title("🔍 Identity Research Tool")
st.caption("AI-assisted compliance research · Powered by GPT-5 with web search")

# --- GDPR Notice ---
st.markdown("""
<div class="gdpr-box">
⚠️ <strong>GDPR / AVG notice:</strong> This tool aggregates publicly available information only,
for legitimate compliance purposes. All results require human analyst review before any action.
All searches are logged. Do not use without a valid legal basis.
</div>
""", unsafe_allow_html=True)

# --- Sidebar: API Key ---
with st.sidebar:
    st.header("⚙️ Configuration")
    api_key = st.text_input("OpenAI API Key", type="password", help="Your OpenAI API key (not stored)")
    st.divider()
    st.markdown("**Model:** gpt-4o-search-preview")
    st.markdown("**Search:** Web search enabled")
    st.markdown("**Output:** Structured JSON")
    st.divider()
    st.caption("v1.0 MVP · EU GDPR Compliant")

# --- Input Form ---
st.subheader("Subject Information")

col1, col2 = st.columns(2)
with col1:
    full_name   = st.text_input("Full name *", placeholder="Jan de Vries")
    city_region = st.text_input("City / Region *", placeholder="Amsterdam, Netherlands")
with col2:
    age         = st.text_input("Age (optional)", placeholder="42")
    employer    = st.text_input("Employer (optional)", placeholder="ING Bank")

context = st.text_input(
    "Research context (optional)",
    placeholder="Mortgage application review · loan €450,000"
)

# Analyst sign-off
analyst_name = st.text_input("Analyst name (for audit log)", placeholder="Your name")

run_btn = st.button("🔍 Run Identity Research", type="primary", use_container_width=True)

# --- Run ---
if run_btn:
    if not api_key:
        st.error("Please enter your OpenAI API key in the sidebar.")
        st.stop()
    if not full_name or not city_region:
        st.error("Full name and city/region are required.")
        st.stop()
    if not analyst_name:
        st.warning("No analyst name entered — proceeding without attribution.")

    with st.spinner("Running research pipeline with GPT-5 web search…"):
        result, error = run_research(
            api_key=api_key,
            name=full_name,
            city=city_region,
            age=age,
            employer=employer,
            context=context
        )

    if error:
        st.error(f"Error: {error}")
        st.stop()

    # --- Audit log entry ---
    audit_entry = {
        "timestamp": datetime.now().isoformat(),
        "analyst": analyst_name or "unknown",
        "subject_name": full_name,
        "subject_city": city_region,
        "context": context
    }
    with open("audit_log.jsonl", "a") as f:
        f.write(json.dumps(audit_entry) + "\n")

    # ============================
    # RESULTS
    # ============================
    st.divider()
    st.markdown("""
    <div class="review-box">
    👁 <strong>Human review required.</strong>
    This report was generated by AI from public sources only.
    A qualified analyst must review all findings before any decision is made.
    </div>
    """, unsafe_allow_html=True)

    st.subheader(f"Report: {full_name} · {city_region}")
    st.caption(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} · Analyst: {analyst_name or '—'}")

    # --- Confidence Score ---
    score = int(result.get("confidence_score", 0))
    verdict = result.get("confidence_verdict", "Unknown")
    reasoning = result.get("confidence_reasoning", "")

    col_score, col_info = st.columns([1, 3])
    with col_score:
        color = "#22c55e" if score >= 75 else "#f59e0b" if score >= 45 else "#ef4444"
        st.markdown(f"<div class='score-badge' style='color:{color}'>{score}</div>", unsafe_allow_html=True)
        st.caption("Confidence score /100")
    with col_info:
        st.markdown(f"**{verdict} confidence**")
        st.write(reasoning)
        st.progress(score / 100)

    st.divider()

    # --- Sections ---
    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("#### 👤 Identity matches")
        items = result.get("identity_matches", [])
        if items:
            for m in items:
                st.markdown(f"**{m.get('name','')}** `{m.get('confidence','')}`")
                st.caption(m.get("description", ""))
        else:
            st.caption("Insufficient data")

        st.markdown("#### 💼 Professional profiles")
        items = result.get("professional_profiles", [])
        if items:
            for p in items:
                st.markdown(f"**{p.get('role','')}** @ {p.get('company','')}")
                st.caption(f"{p.get('platform','')} · {p.get('url_hint','')}")
        else:
            st.caption("Insufficient data")

        st.markdown("#### 🏢 Business records")
        items = result.get("business_records", [])
        if items:
            for b in items:
                st.markdown(f"**{b.get('entity','')}** — {b.get('role','')}")
                st.caption(f"Status: {b.get('status','')} · Source: {b.get('source','')}")
        else:
            st.caption("Insufficient data")

    with col_b:
        st.markdown("#### 📰 Media mentions")
        items = result.get("media_mentions", [])
        if items:
            for m in items:
                sentiment_icon = {"positive":"🟢","neutral":"⚪","negative":"🔴"}.get(m.get("sentiment",""), "⚪")
                st.markdown(f"{sentiment_icon} **{m.get('title','')}**")
                st.caption(f"{m.get('source','')} · {m.get('date','')}")
                st.write(m.get("summary",""))
        else:
            st.caption("Insufficient data")

        st.markdown("#### 🌐 Social media")
        items = result.get("social_media_presence", [])
        if items:
            for s in items:
                st.markdown(f"**{s.get('platform','')}**")
                st.caption(s.get("description",""))
        else:
            st.caption("Insufficient data")

    # --- Risk Flags ---
    st.markdown("#### 🚨 Risk flags")
    flags = result.get("risk_flags", [])
    if flags:
        for f in flags:
            sev = f.get("severity", "low")
            icon = {"high":"⛔","medium":"⚠️","low":"ℹ️"}.get(sev, "ℹ️")
            st.markdown(
                f"<div class='risk-{sev}'>{icon} <strong>[{sev.upper()}] {f.get('category','')}</strong><br>{f.get('description','')}</div>",
                unsafe_allow_html=True
            )
    else:
        st.success("No risk flags identified.")

    # --- Sources ---
    st.markdown("#### 🔗 Sources")
    sources = result.get("sources", [])
    if sources:
        for s in sources:
            url = s.get("url","#")
            name = s.get("name", url)
            stype = s.get("type","")
            st.markdown(f"- [{name}]({url}) `{stype}`")
    else:
        st.caption("No sources recorded.")

    # --- PDF + JSON Export ---
    st.divider()
    col_pdf, col_json = st.columns(2)

    with col_pdf:
        try:
            pdf_bytes = generate_pdf(result, full_name, city_region, analyst_name)
            st.download_button(
                label="⬇️ Download PDF rapport",
                data=pdf_bytes,
                file_name=f"rapport_{full_name.replace(' ','_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
        except Exception as e:
            st.warning(f"PDF generatie mislukt: {e}")

    with col_json:
        st.download_button(
            label="⬇️ Download JSON",
            data=json.dumps(result, indent=2, ensure_ascii=False),
            file_name=f"report_{full_name.replace(' ','_')}_{datetime.now().strftime('%Y%m%d_%H%M')}.json",
            mime="application/json",
            use_container_width=True
        )

    with st.expander("📄 Raw JSON rapport bekijken"):
        st.json(result)
